In [13]:
import pandas as pd

In [14]:
from sqlalchemy import create_engine, engine


db_string = 'mysql+pymysql://root:!wMoU9lBdLZWW6Y8@o8ukkP9TliImN.h.filess.io:58202/MLS'

engine = create_engine(db_string)

sql_query = "SELECT player_id, name FROM players_general"
name_id_df = pd.read_sql_query(sql_query, con=engine)
print(name_id_df.head())

   player_id            name
0          0     J. Pantemis
1        250      D. Beckham
2        330        R. Keane
3        432  S. Miglioranzi
4        560      B. Corradi

In [15]:
name_id_df = name_id_df.rename(columns={'player_id': 'id'})

In [16]:
match_outfield = pd.read_csv('data/raw/matches/players/outfield/master_outfield.csv')

match_gk = pd.read_csv('data/raw/matches/players/gk/master_gk.csv')

In [17]:
matches = pd.read_csv('data/raw/matches/match_data/master_match_data.csv')

In [18]:
matches_dates = matches[['match_id', 'date']].copy()

matches_dates

      match_id        date
0     919a513b  2025-05-04
1     4cb316bb  2025-05-10
2     54fc52e2  2024-07-17
3     0fcc6367  2024-09-14
4     56fecf55  2024-10-02
...        ...         ...
997   ad96ca33  2025-03-22
998   d63a2051  2024-05-11
999   66521dfa  2024-04-21
1000  5e66403b  2024-10-05
1001  c4772769  2024-03-10

[1002 rows x 2 columns]

In [19]:
match_outfield_og = match_outfield.copy()

match_gk_og = match_gk.copy()

name_id_df_og = name_id_df.copy()

In [20]:
#### add date to match_outfield and match_gk

match_outfield = match_outfield.merge(matches_dates, on='match_id', how='left')

match_gk = match_gk.merge(matches_dates, on='match_id', how='left')

In [21]:
import pandas as pd
import unicodedata

# ── 0. Config ────────────────────────────────────────────────────────────────
PLAYER_ID_MAP = {
    'a alves santos':           263947,
    'e da silva ferreira':      234505,
    'a rodrigues de oliveira':  263784,
    'c carrasquilla':           243544,
    'y gomez':                  224396,
    'j artur':                  234122,
    'j de lima junior':         234122,
    'd de sousa britto':        238604,
    'j klauss':                 242998,
    'j mior':                   205953,
    'p martins':                77657,
    'k ferreira':               241487,
    'm dos santos silva':       274396,
    'r benetti':                215643,
    'r gregorio teixeira':      247027,
    'l diaz espinoza':          251387,
    'j klein iii':              275485,
    'a oyirwoth':               15494258,
    'j reginaldo':      70170,
    'r cabral':         192397,
    'k kim':            203002,
    'm cafumana':       251894,
    'n pelae cardoso':  225529,
    'j berrocal':       240859,
    's suleymanov':     240226,
    'l deedson': 252416,
    'b farkarlun':  72009,   
    'h martinez':   241569,  
    'j fortune':    274273, 
    'm agyemang':   274685,  
    'n miller':     247648,
    'o awodesu':    76912, 
    'q ordonez':    263679, 
    'g santos':     226495,
    'v costa de brito': 232388,
    'w abou ali': 242515,
    'g dillon': 278874,
    'b souza': 240332,
    'c sullivan': 999999  # placeholder, needs ID
}

In [ ]:
# ── 1. Norm function ─────────────────────────────────────────────────────────
def norm(s):
    if pd.isna(s):
        return ""
    s = str(s).lower().strip()
    s = s.replace(".", "").replace("-", " ").replace("'", "")
    s = unicodedata.normalize('NFKD', s)
    s = s.encode('ascii', errors='ignore').decode('utf-8')
    s = s.strip()
    parts = s.split()
    if len(parts) > 1:
        s = parts[0][0] + ' ' + ' '.join(parts[1:])
    return s

# ── 2. Fresh copies of original dfs ──────────────────────────────────────────
mop = match_outfield_og.copy()
mgp = match_gk_og.copy()
ni = name_id_df_og.copy()


# ── 4. Normalize name columns ─────────────────────────────────────────────────
mop['name_norm'] = mop['player_name'].apply(norm)
mop['club_norm'] = mop['club'].apply(norm)
mgp['name_norm'] = mgp['name'].apply(norm)
mgp['team_abbr_norm'] = mgp['team_abbr'].apply(norm)
ni['name_norm'] = ni['name'].apply(norm)

# ── 5. Pass 1: name + most recent snapshot BEFORE match date ──────────────────
df1 = mop.merge(
    pl[['id', 'name_norm', 'date']],
    on='name_norm',
    how='left',
    suffixes=('_match', '_player')
)
df1 = df1[df1['date_player'] <= df1['date_match']]
df1 = (df1.sort_values('date_player', ascending=False)
          .drop_duplicates(subset=['match_id', 'name_norm'], keep='first'))

id_lookup_1 = df1.set_index(['match_id', 'name_norm'])['id']
mp['player_id'] = mp.set_index(['match_id', 'name_norm']).index.map(id_lookup_1)

print(f"Pass 1 — unmatched: {mp['player_id'].isna().sum()} rows, {mp[mp['player_id'].isna()]['player_name'].nunique()} unique")

# ── 6. Pass 2: name + closest snapshot in EITHER direction ────────────────────
mask = mp['player_id'].isna()
df2 = mp[mask].merge(
    pl[['id', 'name_norm', 'date']],
    on='name_norm',
    how='left',
    suffixes=('_match', '_player')
)
df2['date_diff'] = (df2['date_player'] - df2['date_match']).abs()
df2 = (df2.sort_values('date_diff')
          .drop_duplicates(subset=['match_id', 'name_norm'], keep='first'))

id_lookup_2 = df2.set_index(['match_id', 'name_norm'])['id']
mp.loc[mask, 'player_id'] = (
    mp[mask].set_index(['match_id', 'name_norm']).index.map(id_lookup_2)
)

print(f"Pass 2 — unmatched: {mp['player_id'].isna().sum()} rows, {mp[mp['player_id'].isna()]['player_name'].nunique()} unique")

# ── 7. Pass 3: name_id_df lookup ─────────────────────────────────────────────
mask = mp['player_id'].isna()
ni_lookup = ni.drop_duplicates(subset='name_norm').set_index('name_norm')['id']
mp.loc[mask, 'player_id'] = mp.loc[mask, 'name_norm'].map(ni_lookup)

print(f"Pass 3 — unmatched: {mp['player_id'].isna().sum()} rows, {mp[mp['player_id'].isna()]['player_name'].nunique()} unique")

# ── 8. Pass 4: manual ID map ──────────────────────────────────────────────────
mask = mp['player_id'].isna()
mp.loc[mask, 'player_id'] = mp.loc[mask, 'name_norm'].map(PLAYER_ID_MAP)

print(f"Pass 4 — unmatched: {mp['player_id'].isna().sum()} rows, {mp[mp['player_id'].isna()]['player_name'].nunique()} unique")

# ── 9. Final summary ──────────────────────────────────────────────────────────
total = len(mp)
matched = mp['player_id'].notna().sum()
unmatched = mp[mp['player_id'].isna()]
print(f"\nFinal — {matched}/{total} matched ({matched/total*100:.1f}%)")
print(f"Unique unmatched: {mp[mp['player_id'].isna()]['player_name'].nunique()}")

# ── 10. Save missing for scraping ─────────────────────────────────────────────
(mp[mp['player_id'].isna()][['player_name', 'club']]
 .drop_duplicates()
 .sort_values(['club', 'player_name'])
 .to_csv('missing_players_final.csv', index=False))

# ── 11. Clean up helper columns and push to DB ────────────────────────────────
mp = mp.drop(columns=['name_norm', 'club_norm'], errors='ignore')
mp = mp.where(mp.notna(), other=None)

In [17]:
#### find players not matched before and after 2026 cutoff

unmatched_before_26 = mp[(mp['player_id'].isna()) & (mp['date'] < '2026-01-01')]
unmatched_after_26 = mp[(mp['player_id'].isna()) & (mp['date'] >= '2026-01-01')]

unmatched_before_26

,match_id,date,player_name,minutes,goals,expected_goals,shot_conv_perc,on_target,pass_perc,assists,...,goals_against,expected_goals_against,Pass,gk_throws,gk_long_balls,gk_launches,GK,corners_conceded,club,player_id
1064,9f7537a0,2025-10-18,G. Diarbian,0,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ne,NaN
1180,63f77bac,2025-10-12,A. González,0,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,atx,NaN
1205,56694b42,2025-10-11,T. Sandy Jr.,0,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,orl,NaN
1241,b2a7b06b,2025-10-11,P. Kingston,10,0,0.0,0.0,0.0,50.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,NaN
1248,7f9d56d1,2025-10-11,R. Montenegro,0,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mia,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40201,ca447a56,2024-03-23,S. Lapkes,0,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,clb,NaN
40252,3f0c18ee,2024-03-23,R. Montenegro,0,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mia,NaN
40258,3f0c18ee,2024-03-23,J. Casas de Abadal,16,0,0.0,0.0,0.0,86.7,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mia,NaN
40583,1dde04c3,2024-03-16,C. Olivares,0,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,stl,NaN
41039,ba9c4d64,2024-03-02,V. Noël,0,0,0.0,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,atx,NaN

In [22]:
### count how many times each unmatched player appears before and after 2026 cutoff

print("Unmatched players before 2026 cutoff:")
print(unmatched_before_26['player_name'].value_counts())
print("\nUnmatched players after 2026 cutoff:")
print(unmatched_after_26['player_name'].value_counts())

Unmatched players before 2026 cutoff:
player_name
C. Olivares         13
D. Konincks          6
L. Frugis Afonso     6
J. Dilrosun          6
M. Kerkvliet         6
                    ..
É. Díaz              1
S. Suarez            1
C. Abadia-Reda       1
T. Fleming           1
V. Noël              1
Name: count, Length: 90, dtype: int64

Unmatched players after 2026 cutoff:
player_name
J. Ruvalcaba            3
T. Calheira             3
M. dos Santos           3
E. Aristizábal          3
B. Zamblé               3
A. Mehmeti              3
S. Eustáquio            3
E. Báez                 3
Z. Loyo Reynaga         3
S. Donovan              3
I. da Silva Nogueira    3
J. Sery Larsen          3
E. Horvath              3
A. Anello               3
M. Dos Santos           3
N. Streit               2
M. Arana                2
A. Resch                2
J. Valiente             2
T. Putt                 2
T. Werner               2
R. Mesalles             2
J. Ellis                2
A. Smoliakov            2
J. Da                   2
C. Abadia-Reda          1
D. Judelson             1
E. Dymora               1
A. Shaw                 1
J. Mussenden            1
B. Kuscevic             1
Z. Campagnolo           1
N. Adimabua             1
A. Aravena              1
C. Sabaly               1
G. Sequera              1
E. Izoita               1
M. Galarza              1
L. Johnsen              1
C. Ondo                 1
P. Lurot                1
T. Majub                1
Name: count, dtype: int64

In [ ]:
### see players in both groups

before_names = set(unmatched_before_26['player_name'].unique())
after_names = set(unmatched_after_26['player_name'].unique())
both_groups = before_names.intersection(after_names)
print("\nPlayers unmatched both before and after 2026 cutoff:")
print(both_groups)

In [23]:
mp.to_csv('../../data/interim/matches/players/cleaned_mls_match_player_stats_031926_with_ids.csv', index=False)

In [45]:
mp.columns

Index(['match_id', 'date', 'player_name', 'minutes', 'goals', 'expected_goals',
       'shot_conv_perc', 'on_target', 'pass_perc', 'assists', 'passes',
       'cross', 'corner_kick', 'key_pass', 'aerial', 'aerial_perc', 'fouls',
       'fouls_against', 'offside', 'yellow_card', 'red_card', 'side',
       'goals_saved', 'goals_against', 'expected_goals_against', 'Pass',
       'gk_throws', 'gk_long_balls', 'gk_launches', 'GK', 'corners_conceded',
       'club', 'player_id'],
      dtype='object')

In [41]:
from sqlalchemy import insert, Table, MetaData

stmt = insert(match_player_stats).prefix_with("IGNORE").values(chunk.to_dict(orient='records'))
conn.execute(stmt)
conn.commit()

print("Done — match_player_stats pushed to DB")

NameError: name 'match_player_stats' is not defined

In [22]:
### find date range of unmatched players' matches for targeted scraping

dates = mp[mp['player_id'].isna()]
dates = dates[['date', 'player_name']]
print("Date range of unmatched players' matches:")
print("Earliest:", dates.min())
print("Latest:", dates.max())

dates

Date range of unmatched players' matches:
Earliest: date           2024-02-24 00:00:00
player_name              A. Anello
dtype: object
Latest: date           2026-03-08 00:00:00
player_name                É. Díaz
dtype: object

            date         player_name
9     2026-03-08        J. Ruvalcaba
12    2026-03-08          A. Mehmeti
15    2026-03-08       M. Dos Santos
19    2026-03-08          E. Horvath
49    2026-03-07          G. Sequera
...          ...                 ...
40201 2024-03-23           S. Lapkes
40252 2024-03-23       R. Montenegro
40258 2024-03-23  J. Casas de Abadal
40583 2024-03-16         C. Olivares
41039 2024-03-02             V. Noël

[363 rows x 2 columns]

In [24]:
## how many names and how many matches do the unmatched players have?

missing_player_ids = mp[mp['player_id'].isna()]
unmatched_counts = missing_player_ids['player_name'].value_counts()

names = unmatched_counts.index.tolist()
counts = unmatched_counts.values.tolist()

print("Unique unmatched players and their match counts:")
for name, count in zip(names, counts):
    print(f"{name}: {count} matches")
    


print('how many unique unmatched player names are there?')
print(len(names))

Unique unmatched players and their match counts:
C. Sullivan: 43 matches
C. Olivares: 13 matches
W. Abou Ali: 8 matches
G. Dillon: 7 matches
S. Lapkes: 6 matches
M. Kerkvliet: 6 matches
B. Souza: 6 matches
J. Dilrosun: 6 matches
D. Konincks: 6 matches
M. O'Neill: 6 matches
L. Frugis Afonso: 6 matches
V. Costa de Brito: 6 matches
J. Ellis: 5 matches
C. Lozano: 5 matches
C. Staniland: 4 matches
A. Randell: 4 matches
H. Osorio: 4 matches
M. Sullivan: 4 matches
A. Mehmeti: 4 matches
D. Gonzalez: 4 matches
M. Dias: 4 matches
D. Amadou: 4 matches
N. Sullivan: 3 matches
S. George: 3 matches
M. dos Santos: 3 matches
N. Fernández Mercau: 3 matches
J. Santiago: 3 matches
E. Aristizábal: 3 matches
S. Musu: 3 matches
D. Iskenderian: 3 matches
R. Fisher: 3 matches
W. Speel: 3 matches
A. Coupland: 3 matches
J. Selemani: 3 matches
K. Romanshyn: 3 matches
J. Marques Siqueira: 3 matches
P. Molinari: 3 matches
A. Rosa: 3 matches
N. Van Rijn: 3 matches
J. Ruvalcaba: 3 matches
S. Eustáquio: 3 matches
E. Horvath: 3 matches
E. Báez: 3 matches
I. da Silva Nogueira: 3 matches
J. Sery Larsen: 3 matches
A. Anello: 3 matches
Z. Loyo Reynaga: 3 matches
B. Zamblé: 3 matches
M. Dos Santos: 3 matches
S. Donovan: 3 matches
T. Calheira: 3 matches
R. Neri: 2 matches
N. Adnan: 2 matches
A. Batioja: 2 matches
K. Linhares: 2 matches
P. Amponsah: 2 matches
S. Mazzaferro: 2 matches
P. Cruz: 2 matches
R. Montenegro: 2 matches
V. Enriquez Velazquez: 2 matches
R. Carmichael: 2 matches
J. Da: 2 matches
M. Khan: 2 matches
J. Batiz: 2 matches
A. Dumitru: 2 matches
J. Casas de Abadal: 2 matches
J. Herdman: 2 matches
Z. Campagnolo: 2 matches
N. Streit: 2 matches
A. Smoliakov: 2 matches
T. Putt: 2 matches
E. O'Brien: 2 matches
P. Kingston: 2 matches
A. González: 2 matches
G. Diarbian: 2 matches
M. Arana: 2 matches
C. Abadia-Reda: 2 matches
L. Ulrich: 2 matches
J. Valiente: 2 matches
R. Mesalles: 2 matches
A. Resch: 2 matches
T. Werner: 2 matches
V. Hlyut: 2 matches
C. Kachwele: 2 matches
L. Hille: 1 matches
T. Clegg: 1 matches
S. Karani: 1 matches
G. Sequera: 1 matches
G. DeLibera: 1 matches
M. Vargas: 1 matches
D. Judelson: 1 matches
P. Mangione: 1 matches
E. Jääskeläinen: 1 matches
K. Storlie: 1 matches
A. Shaw: 1 matches
E. Dymora: 1 matches
P. Elias: 1 matches
R. Tori: 1 matches
F. McRobb: 1 matches
J. Mussenden: 1 matches
T. Majub: 1 matches
O. Marquez: 1 matches
R. O'Driscoll: 1 matches
S. Basabe: 1 matches
J. Altobelli: 1 matches
B. Kuscevic: 1 matches
S. Annor Gyamfi: 1 matches
T. Sandy Jr.: 1 matches
J. Harms: 1 matches
P. Holbrook: 1 matches
N. Adimabua: 1 matches
T. Fleming: 1 matches
É. Díaz: 1 matches
C. Sabaly: 1 matches
D. Russo: 1 matches
A. Pelayo: 1 matches
L. Pruter: 1 matches
A. Causey: 1 matches
M. Galarza: 1 matches
K. Rizvanovich: 1 matches
L. Johnsen: 1 matches
P. Lurot: 1 matches
R. Lynch: 1 matches
D. Odle: 1 matches
G. Rayo: 1 matches
E. Berumen: 1 matches
A. Aravena: 1 matches
O. Herrera: 1 matches
C. Ondo: 1 matches
E. Izoita: 1 matches
H. Ayari: 1 matches
S. Suarez: 1 matches
V. Noël: 1 matches
how many unique unmatched player names are there?
133

In [25]:
### find unmatched players with matches before 2026

unmatched_before_2026 = mp[(mp['player_id'].isna()) & (mp['date'] < '2026-01-01')]
print("Unmatched players with matches before 2026:")
unmatched_before_2026 = unmatched_before_2026[['player_name', 'date', 'club']].drop_duplicates().sort_values('date')
unmatched_before_2026

Unmatched players with matches before 2026:

               player_name       date  club
20587      S. Annor Gyamfi 2024-02-24   hou
20582          D. Gonzalez 2024-02-24   hou
20214           J. Herdman 2024-03-02   van
41039              V. Noël 2024-03-02   atx
19975       D. Iskenderian 2024-03-09   rsl
...                    ...        ...   ...
21861  J. Marques Siqueira 2025-10-18  lafc
21697         M. Kerkvliet 2025-10-18   rsl
1064           G. Diarbian 2025-10-18    ne
21880          P. Kingston 2025-10-18   sea
1021              B. Souza 2025-10-18   cin

[272 rows x 3 columns]

In [26]:
unmatched

,match_id,date,player_name,minutes,goals,expected_goals,shot_conv_perc,on_target,pass_perc,assists,...,Pass,gk_throws,gk_long_balls,gk_launches,GK,corners_conceded,club,name_norm,club_norm,player_id
9,c1d67317,2026-03-08,J. Ruvalcaba,90,0,0.00,0.0,0.0,73.3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,rbny,j ruvalcaba,rbny,NaN
12,c1d67317,2026-03-08,A. Mehmeti,90,0,0.33,1.0,0.0,80.7,0,...,NaN,NaN,NaN,NaN,NaN,NaN,rbny,a mehmeti,rbny,NaN
15,c1d67317,2026-03-08,M. Dos Santos,61,0,0.00,0.0,0.0,82.5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,rbny,m dos santos,rbny,NaN
19,c1d67317,2026-03-08,E. Horvath,90,1,0.00,NaN,NaN,NaN,0,...,92.1,4.0,0.0,0.0,0.0,0.0,rbny,e horvath,rbny,NaN
49,fc3f246b,2026-03-07,G. Sequera,82,0,0.02,1.0,0.0,61.9,0,...,NaN,NaN,NaN,NaN,NaN,NaN,phi,g sequera,phi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40201,ca447a56,2024-03-23,S. Lapkes,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,clb,s lapkes,clb,NaN
40252,3f0c18ee,2024-03-23,R. Montenegro,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,mia,r montenegro,mia,NaN
40258,3f0c18ee,2024-03-23,J. Casas de Abadal,16,0,0.00,0.0,0.0,86.7,0,...,NaN,NaN,NaN,NaN,NaN,NaN,mia,j casas de abadal,mia,NaN
40583,1dde04c3,2024-03-16,C. Olivares,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,stl,c olivares,stl,NaN
41039,ba9c4d64,2024-03-02,V. Noël,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,atx,v noel,atx,NaN

In [27]:
# Extract last name from name_norm (everything after first initial)
def get_last_name(s):
    parts = str(s).split()
    return ' '.join(parts[1:]) if len(parts) > 1 else s

unmatched['last_name'] = unmatched['name_norm'].apply(get_last_name)
pl['last_name'] = pl['name_norm'].apply(get_last_name)


# Merge on last_name + team
df_last = unmatched.merge(
    pl[['id', 'name', 'name_norm', 'last_name', 'team_abbr_norm', 'date']],
    left_on=['last_name', 'club_norm'],
    right_on=['last_name', 'team_abbr_norm'],
    how='inner',
    suffixes=('_match', '_player')
)

# Keep only snapshots before or on match date
df_last = df_last[df_last['date_player'] <= df_last['date_match']]

# Keep most recent snapshot
df_last = (df_last.sort_values('date_player', ascending=False)
                  .drop_duplicates(subset=['match_id', 'name_norm_match'], keep='first'))

# Show matches with dates for review
print(df_last[['player_name', 'date_match', 'club', 'name', 'team_abbr_norm', 'date_player', 'id']]
      .drop_duplicates(subset=['player_name', 'name'])
      .sort_values('player_name')
      .to_string(index=False))

  player_name date_match club          name team_abbr_norm date_player     id
  C. Sullivan 2026-03-07  phi   Q. Sullivan            phi  2026-03-05 260547
M. dos Santos 2026-03-01  mia C. dos Santos            mia  2025-02-04 267636
      P. Cruz 2025-04-05  hou       D. Cruz            hou  2011-08-30 190676

In [ ]:
mp = mp.dr

In [28]:
unmatched_names = match_players[match_players['id'].isna()]['player_name'].unique()

for name in unmatched_names[:30]:
    norm_name = norm(name)
    # Get last name only
    last = norm_name.split()[-1]
    
    candidates = players[players['name_norm'].str.contains(last, na=False)][['id', 'name', 'team_abbr']].drop_duplicates()
    
    if not candidates.empty:
        print(f"\n{'─'*50}")
        print(f"UNMATCHED:  {name}  ({norm_name})")
        print(f"CANDIDATES:")
        print(candidates.to_string(index=False))

KeyError: 'id'

In [163]:
missing_final = (match_players[match_players['player_id'].isna()][['player_name', 'club']]
                 .drop_duplicates()
                 .sort_values(['club', 'player_name']))
                 
missing_final.to_csv('missing_players_final.csv', index=False)
print(f"{len(missing_final)} player/club combos to scrape")

171 player/club combos to scrape

In [164]:
### find percentage of unmatched players with multiple matches (i.e. more important to prioritize)

unmatched = match_players[match_players['player_id'].isna()]
unmatched_counts = unmatched.groupby('player_name')['match_id'].nunique()

print(f"{(unmatched_counts > 1).mean()*100:.1f}% of unmatched players have multiple matches")

names = list(unmatched_counts[unmatched_counts > 1].sort_values(ascending=False).index)

70.8% of unmatched players have multiple matches

In [165]:
### print names of unmatched players with 4+ matches

print("Unmatched players with 4+ matches:")
for name in names:
    count = unmatched_counts[name]
    if count >= 2:
        print(f"{name}: {count} matches")

Unmatched players with 4+ matches:
A. Alves Santos: 64 matches
J. Klauss: 64 matches
E. Da Silva Ferreira: 62 matches
A. Rodrigues de Oliveira: 58 matches
J. Mior: 47 matches
D. De Sousa Britto: 45 matches
C. Sullivan: 43 matches
J. De Lima Junior: 38 matches
R. Cabral: 37 matches
Y. Gómez: 36 matches
S. Suleymanov: 36 matches
M. dos Santos Silva: 33 matches
R. Benetti: 32 matches
R. Gregório Teixeira: 31 matches
K. Ferreira: 31 matches
P. Martins: 30 matches
C. Carrasquilla: 28 matches
L. Diaz Espinoza: 25 matches
J. Reginaldo: 22 matches
K. Kim: 20 matches
M. Cafumana: 19 matches
J. de Lima Júnior: 15 matches
J. Artur: 14 matches
N. Pelae Cardoso: 14 matches
C. Olivares: 13 matches
J. Klein III: 13 matches
A. Oyirwoth: 13 matches
J. Berrocal: 13 matches
L. Deedson: 9 matches
W. Abou Ali: 8 matches
B. Farkarlun: 8 matches
G. Dillon: 7 matches
S. Lapkes: 6 matches
B. Souza: 6 matches
J. Dilrosun: 6 matches
M. O'Neill: 6 matches
V. Costa de Brito: 6 matches
D. Konincks: 6 matches
M. Kerkvliet: 6 matches
L. Frugis Afonso: 6 matches
J. Ellis: 5 matches
C. Lozano: 5 matches
J. Fortune: 5 matches
M. Sullivan: 4 matches
A. Randell: 4 matches
Q. Ordoñez: 4 matches
C. Staniland: 4 matches
D. Amadou: 4 matches
A. Mehmeti: 4 matches
D. Gonzalez: 4 matches
H. Martínez: 4 matches
H. Osorio: 4 matches
M. Dias: 4 matches
S. Eustáquio: 3 matches
N. Van Rijn: 3 matches
N. Sullivan: 3 matches
S. George: 3 matches
N. Miller: 3 matches
O. Awodesu: 3 matches
S. Donovan: 3 matches
R. Fisher: 3 matches
M. dos Santos: 3 matches
S. Musu: 3 matches
A. Coupland: 3 matches
T. Calheira: 3 matches
W. Speel: 3 matches
P. Molinari: 3 matches
M. Dos Santos: 3 matches
N. Fernández Mercau: 3 matches
Z. Loyo Reynaga: 3 matches
J. Santiago: 3 matches
A. Anello: 3 matches
B. Zamblé: 3 matches
J. Ruvalcaba: 3 matches
E. Báez: 3 matches
J. Selemani: 3 matches
J. Sery Larsen: 3 matches
J. Marques Siqueira: 3 matches
M. Agyemang: 3 matches
E. Aristizábal: 3 matches
D. Iskenderian: 3 matches
K. Romanshyn: 3 matches
I. da Silva Nogueira: 3 matches
A. Rosa: 3 matches
E. Horvath: 3 matches
G. Santos: 2 matches
S. Mazzaferro: 2 matches
J. Batiz: 2 matches
G. Diarbian: 2 matches
E. O'Brien: 2 matches
M. Arana: 2 matches
T. Putt: 2 matches
T. Werner: 2 matches
R. Neri: 2 matches
V. Enriquez Velazquez: 2 matches
V. Hlyut: 2 matches
A. Batioja: 2 matches
Z. Campagnolo: 2 matches
J. Casas de Abadal: 2 matches
A. González: 2 matches
R. Montenegro: 2 matches
P. Amponsah: 2 matches
L. Ulrich: 2 matches
M. Khan: 2 matches
K. Linhares: 2 matches
A. Smoliakov: 2 matches
N. Adnan: 2 matches
J. Valiente: 2 matches
N. Streit: 2 matches
P. Cruz: 2 matches
R. Mesalles: 2 matches
P. Kingston: 2 matches
C. Abadia-Reda: 2 matches
J. Herdman: 2 matches
C. Kachwele: 2 matches
R. Carmichael: 2 matches
J. Da: 2 matches
A. Dumitru: 2 matches
A. Resch: 2 matches

In [166]:
check_names = ['cabral', 'gomez', 'suleymanov', 'benetti', 'teixeira', 
               'ferreira', 'martins', 'espinoza', 'reginaldo', 'kim',
               'cafumana', 'artur', 'cardoso', 'lima', 'antony', 'evander', 
               'rodrigues', 'joao paulo', 'daniel', 'a carrasquilla', 'j klauss de mello']

for name in check_names:
    results = players[players['name_norm'].str.contains(name, na=False)][['id', 'name', 'team_abbr']].drop_duplicates()
    if not results.empty:
        print(f"\n--- {name} ---")
        print(results.to_string(index=False))

--- cabral ---
    id      name team_abbr
246450 K. Cabral        LA
246450 K. Cabral       COL

--- gomez ---
    id             name team_abbr
138156         H. Gomez       TOR
191240         E. Gomez       TOR
174732         G. Gomez       PHI
219133         A. Gomez       MIN
242736         X. Gomez       MIN
228296         T. Gomez        SJ
138156         H. Gomez        LA
224396 Y. Gomez Andrade       SEA
138156         H. Gomez       SEA
269278         D. Gomez       MIA
233263         S. Gomez       NYC
138156         H. Gomez       COL
142946         C. Gomez       COL
142946         C. Gomez        DC
228296         T. Gomez       RSL
266674         C. Gomez       RSL
266674         A. Gomez       RSL
138156         H. Gomez       SKC
 81827         S. Gomez       SEA

--- suleymanov ---
    id          name team_abbr
240226 M. Suleymanov       SKC

--- ferreira ---
    id        name team_abbr
241487 J. Ferreira       DAL
176380 D. Ferreira       DAL
244832 S. Ferreira       HOU
241487 J. Ferreira       SEA

--- martins ---
    id           name team_abbr
205669   Luis Martins       SKC
205669   Luis Martins       VAN
137494     O. Martins       SEA
207465 Felipe Martins       MTL
233790 Thiago Martins       NYC
152892     T. Martins       COL

--- espinoza ---
    id        name team_abbr
186674 R. Espinoza       SKC
254211 J. Espinoza       CHI
226385 C. Espinoza        SJ
226385 C. Espinoza       NSH

--- kim ---
    id      name team_abbr
180700 K. Kimura      RBNY
180700 K. Kimura       POR
180700 K. Kimura       COL

--- artur ---
    id  name team_abbr
234122 Artur       HOU
234122 Artur       CLB

--- lima ---
    id       name team_abbr
236993    N. Lima       ATX
236993    N. Lima        NE
236757 P. Klimala      RBNY
236993    N. Lima        SJ
 11855    F. Lima        SJ

--- antony ---
    id   name team_abbr
263947 Antony       POR

--- evander ---
    id    name team_abbr
234505 Evander       POR
234505 Evander       CIN

--- rodrigues ---
    id         name team_abbr
263784    Rodrigues        SJ
 69989 B. Rodrigues       SEA

--- daniel ---
    id       name team_abbr
180537 A. Daniels       DAL
243215 A. Daniels       TOR
195071  K. Daniel       PHI
238604     Daniel        SJ

--- a carrasquilla ---
    id            name team_abbr
243544 A. Carrasquilla       HOU

In [174]:
remaining = ['m dos santos silva', 'r benetti', 'r gregorio teixeira',
             'l diaz espinoza', 'j reginaldo', 'k kim', 'm cafumana',
             'j de lima junior', 'n pelae cardoso', 'c olivares',
             'j klein iii', 'a oyirwoth', 'j berrocal', 'l deedson',
             'w abou ali', 'b farkarlun', 'g dillon', 's lapkes',
             'b souza', 'j dilrosun', 'm oneill', 'v costa de brito',
             'd konincks', 'm kerkvliet', 'l frugis afonso']

for name in remaining:
    clubs = (match_players[match_players['name_norm'] == norm(name)]['club']
             .value_counts())
    if not clubs.empty:
        print(f"{name}: {clubs.index[0]} ({clubs.iloc[0]} matches)")

m dos santos silva: hou (33 matches)
r benetti: dal (32 matches)
r gregorio teixeira: mtl (25 matches)
l diaz espinoza: ne (25 matches)
j reginaldo: clt (22 matches)
k kim: sea (20 matches)
m cafumana: dal (19 matches)
j de lima junior: hou (53 matches)
n pelae cardoso: sea (14 matches)
c olivares: stl (13 matches)
j klein iii: stl (13 matches)
a oyirwoth: ne (13 matches)
j berrocal: atl (13 matches)
l deedson: dal (9 matches)
w abou ali: clb (8 matches)
b farkarlun: atx (8 matches)
g dillon: rsl (7 matches)
s lapkes: clb (6 matches)
b souza: cin (6 matches)
j dilrosun: lafc (6 matches)
m oneill: van (6 matches)
v costa de brito: sj (6 matches)
d konincks: chi (6 matches)
m kerkvliet: rsl (6 matches)
l frugis afonso: mia (6 matches)

In [176]:
# Use IDs directly to avoid norm() mangling the mapped values
PLAYER_ID_MAP = {
    'a alves santos':           263947,
    'e da silva ferreira':      234505,
    'a rodrigues de oliveira':  263784,
    'c carrasquilla':           243544,
    'y gomez':                  224396,
    'j artur':                  234122,
    'j de lima junior':         234122,
    'd de sousa britto':        238604,
    'j klauss':                 242998,
    'j mior':                   205953,
    'p martins':                77657,
    'k ferreira':               241487,
    'm dos santos silva':       274396,
    'r benetti':                215643,
    'r gregorio teixeira':      247027,
    'l diaz espinoza':          251387,
    'j klein iii':              275485,
}

# Apply directly — no norm() involved
mask = match_players['player_id'].isna()
match_players.loc[mask, 'player_id'] = (
    match_players.loc[mask, 'name_norm'].map(PLAYER_ID_MAP)
)

print("Still unmatched:", match_players['player_id'].isna().sum())
print("Unique unmatched:", match_players[match_players['player_id'].isna()]['player_name'].nunique())

Still unmatched: 578
Unique unmatched: 150

In [177]:
still = match_players[match_players['player_id'].isna()]['name_norm'].unique()

# Check which of our map keys are still showing as unmatched
for name in PLAYER_ID_MAP.keys():
    if name in still:
        print(f"STILL UNMATCHED (in map but not applied): {name}")

# Show sample of remaining unmatched
print("\nSample of remaining 150:")
print(sorted(still)[:30])

Sample of remaining 150:
['a anello', 'a aravena', 'a batioja', 'a causey', 'a coupland', 'a dumitru', 'a gonzalez', 'a mehmeti', 'a oyirwoth', 'a pelayo', 'a randell', 'a resch', 'a rosa', 'a shaw', 'a smoliakov', 'b farkarlun', 'b kuscevic', 'b souza', 'b zamble', 'c abadia reda', 'c kachwele', 'c lozano', 'c olivares', 'c ondo', 'c sabaly', 'c staniland', 'c sullivan', 'd amadou', 'd gonzalez', 'd iskenderian']

In [178]:
# Check exact name_norm value for j mior rows
print(match_players[match_players['player_name'].str.lower().str.contains('mior')][['player_name', 'name_norm', 'player_id']])

      player_name name_norm  player_id
1231      J. Mior    j mior   205953.0
1549      J. Mior    j mior   205953.0
1847      J. Mior    j mior   205953.0
5436      J. Mior    j mior   205953.0
6069      J. Mior    j mior   205953.0
6508      J. Mior    j mior   205953.0
6866      J. Mior    j mior   205953.0
7864      J. Mior    j mior   205953.0
8504      J. Mior    j mior   205953.0
9692      J. Mior    j mior   205953.0
10151     J. Mior    j mior   205953.0
10768     J. Mior    j mior   205953.0
11087     J. Mior    j mior   205953.0
13818     J. Mior    j mior   205953.0
14118     J. Mior    j mior   205953.0
14552     J. Mior    j mior   205953.0
15040     J. Mior    j mior   205953.0
15338     J. Mior    j mior   205953.0
15807     J. Mior    j mior   205953.0
16590     J. Mior    j mior   205953.0
17127     J. Mior    j mior   205953.0
17702     J. Mior    j mior   205953.0
18316     J. Mior    j mior   205953.0
18986     J. Mior    j mior   205953.0
21869     J. Mior    j mior   205953.0
22696     J. Mior    j mior   205953.0
26700     J. Mior    j mior   205953.0
28034     J. Mior    j mior   205953.0
28275     J. Mior    j mior   205953.0
29014     J. Mior    j mior   205953.0
29515     J. Mior    j mior   205953.0
29870     J. Mior    j mior   205953.0
30169     J. Mior    j mior   205953.0
30745     J. Mior    j mior   205953.0
31362     J. Mior    j mior   205953.0
32112     J. Mior    j mior   205953.0
33857     J. Mior    j mior   205953.0
34295     J. Mior    j mior   205953.0
35064     J. Mior    j mior   205953.0
36354     J. Mior    j mior   205953.0
36742     J. Mior    j mior   205953.0
37436     J. Mior    j mior   205953.0
38011     J. Mior    j mior   205953.0
38131     J. Mior    j mior   205953.0
38684     J. Mior    j mior   205953.0
38762     J. Mior    j mior   205953.0
39309     J. Mior    j mior   205953.0

In [179]:
# Verify 150 unique players account for all 578 rows
unmatched = match_players[match_players['player_id'].isna()]
print("Unmatched rows:", len(unmatched))
print("Unique unmatched players:", unmatched['player_name'].nunique())
print("Avg appearances per missing player:", len(unmatched) / unmatched['player_name'].nunique())

# Check if any are high-frequency enough to worry about
print("\nTop 10 missing by appearances:")
print(unmatched['player_name'].value_counts().head(10))

Unmatched rows: 578
Unique unmatched players: 150
Avg appearances per missing player: 3.8533333333333335

Top 10 missing by appearances:
player_name
C. Sullivan         43
R. Cabral           37
S. Suleymanov       36
J. Reginaldo        22
K. Kim              20
M. Cafumana         19
N. Pelae Cardoso    14
A. Oyirwoth         13
J. Berrocal         13
C. Olivares         13
Name: count, dtype: int64

In [180]:
check = ['r cabral barbosa', 'r cabral', 'cavan sullivan', 'c sullivan']
for name in check:
    result = players[players['name_norm'].str.contains(name.split()[-1], na=False)][['id', 'name', 'team_abbr']].drop_duplicates()
    if not result.empty:
        print(f"\n--- {name} ---")
        print(result.to_string(index=False))

--- r cabral barbosa ---
    id            name team_abbr
247010 Robinho Barbosa       CLB

--- r cabral ---
    id      name team_abbr
246450 K. Cabral        LA
246450 K. Cabral       COL

--- cavan sullivan ---
    id        name team_abbr
260547 Q. Sullivan       PHI

--- c sullivan ---
    id        name team_abbr
260547 Q. Sullivan       PHI

In [ ]:
# Drop the helper columns we added during matching
match_players = match_players.drop(columns=['name_norm', 'name_lookup', 'club_norm'], errors='ignore')

# Final summary
total = len(match_players)
matched = match_players['player_id'].notna().sum()
print(f"Final: {matched}/{total} matched ({matched/total*100:.1f}%)")

# Save missing for scraping
(match_players[match_players['player_id'].isna()][['player_name', 'club']]
 .drop_duplicates()
 .sort_values(['club', 'player_name'])
 .to_csv('missing_players_final.csv', index=False))

# Push to DB
match_players = match_players.where(match_players.notna(), other=None)

Final: 40845/41423 matched (98.6%)

NameError: name 'insert' is not defined

In [185]:
match_players.columns

Index(['match_id', 'date', 'player_name', 'minutes', 'goals', 'expected_goals', 'shot_conv_perc', 'on_target', 'pass_perc', 'assists', 'passes', 'cross', 'corner_kick', 'key_pass', 'aerial', 'aerial_perc', 'fouls', 'fouls_against', 'offside', 'yellow_card', 'red_card', 'side', 'goals_saved', 'goals_against', 'expected_goals_against', 'Pass', 'gk_throws', 'gk_long_balls', 'gk_launches', 'GK', 'corners_conceded', 'club', 'player_id'], dtype='object')

In [186]:
match_players.to_csv('../../data/interim/matches/players/match_players_stats_with_ids_032026.csv', index=False)

In [183]:
from sqlalchemy import insert

with engine.connect() as conn:
    for chunk in [match_players[i:i+1000] for i in range(0, len(match_players), 1000)]:
        stmt = insert(match_players).prefix_with("IGNORE").values(chunk.to_dict(orient='records'))
        conn.execute(stmt)
    conn.commit()

print("Done — match_player_stats pushed to DB")

ArgumentError: subject table for an INSERT, UPDATE or DELETE expected, got        match_id       date        player_name  minutes  goals  expected_goals  shot_conv_perc  on_target  pass_perc  assists  passes  cross  corner_kick  key_pass  aerial  aerial_perc  fouls  fouls_against  offside  yellow_card  red_card  side  goals_saved  goals_against  expected_goals_against  Pass  gk_throws  gk_long_balls  gk_launches   GK  corners_conceded  club  player_id
0      c1d67317 2026-03-08          T. Parker        0      0            0.00             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN  rbny   226803.0
1      c1d67317 2026-03-08        J. McCarthy        0      0            0.00             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN  rbny   227909.0
2      c1d67317 2026-03-08          C. Cowell       85      0            0.06             1.0        1.0       65.7        0      23      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN  rbny    73878.0
3      c1d67317 2026-03-08         R. Voloder       90      0            0.04             1.0        0.0       92.1        0      58      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN  rbny   256499.0
4      c1d67317 2026-03-08  J. Marshall-Rutty       77      0            0.02             1.0        0.0       94.6        0      53      0          0.0       0.0     0.0          0.0    1.0              1        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN  rbny   255335.0
...         ...        ...                ...      ...    ...             ...             ...        ...        ...      ...     ...    ...          ...       ...     ...          ...    ...            ...      ...          ...       ...   ...          ...            ...                     ...   ...        ...            ...          ...  ...               ...   ...        ...
41418  91a639d5 2024-02-21        N. Caliskan       17      0            0.00             0.0        0.0       88.2        0      15      0          0.0       0.0     0.0          0.0    0.0              1        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN   rsl   275645.0
41419  91a639d5 2024-02-21         F. Barajas       24      0            0.00             0.0        0.0       81.8        0       9      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN   rsl    70857.0
41420  91a639d5 2024-02-21           E. Eneli       90      0            0.00             0.0        0.0       93.3        0      42      0          0.0       0.0     0.0          0.0    0.0              1        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN   rsl   274970.0
41421  91a639d5 2024-02-21         N. Palacio       66      0            0.02             1.0        0.0       92.0        0      46      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN   rsl   264433.0
41422  91a639d5 2024-02-21         Z. MacMath       90      6            0.00             NaN        NaN        NaN        0       0      0          NaN       NaN     NaN          NaN    NaN              0        0          NaN         0  away          2.0            0.0                    25.0  75.8        9.0            0.0          0.0  0.0               0.0   rsl   201940.0

[41423 rows x 33 columns].

In [187]:
check = ['joao pedro', 'l diaz', 'luis diaz', 'k kim', 'kee hee kim',
         'n pelae cardoso', 'm cafumana', 'r gregorio teixeira',
         'c olivares', 'j klein', 'a oyirwoth', 'j berrocal',
         'l deedson', 'w abou ali', 'b farkarlun', 'b souza',
         'j dilrosun', 'm oneill', 'v costa de brito', 
         'd konincks', 'm kerkvliet', 'l frugis afonso', 'rafael']

for name in check:
    result = players[players['name_norm'].str.contains(name, na=False)][['id', 'name', 'team_abbr']].drop_duplicates()
    if not result.empty:
        print(f"\n--- {name} ---")
        print(result.to_string(index=False))
    else:
        print(f"\n--- {name} --- NOT FOUND")

--- joao pedro --- NOT FOUND

--- l diaz ---
    id    name team_abbr
251387 L. Diaz        NE
251387 L. Diaz       CLB
251387 L. Diaz       COL

--- luis diaz --- NOT FOUND

--- k kim ---
    id      name team_abbr
180700 K. Kimura      RBNY
180700 K. Kimura       POR
180700 K. Kimura       COL

--- kee hee kim --- NOT FOUND

--- n pelae cardoso --- NOT FOUND

--- m cafumana --- NOT FOUND

--- r gregorio teixeira --- NOT FOUND

--- c olivares --- NOT FOUND

--- j klein ---
    id     name team_abbr
275485 J. Klein       STL

--- a oyirwoth --- NOT FOUND

--- j berrocal --- NOT FOUND

--- l deedson --- NOT FOUND

--- w abou ali --- NOT FOUND

--- b farkarlun --- NOT FOUND

--- b souza --- NOT FOUND

--- j dilrosun --- NOT FOUND

--- m oneill --- NOT FOUND

--- v costa de brito --- NOT FOUND

--- d konincks --- NOT FOUND

--- m kerkvliet --- NOT FOUND

--- l frugis afonso --- NOT FOUND

--- rafael ---
    id   name team_abbr
203120 Rafael        DC
192397 Rafael       RSL

In [170]:
PLAYER_NAME_MAP = {
    'a alves santos':           'antony',
    'e da silva ferreira':      'evander',
    'a rodrigues de oliveira':  'rodrigues',
    'c carrasquilla':           'a carrasquilla',
    'y gomez':                  'y gomez andrade',
    'j artur':                  'artur',
    'j de lima junior':         'artur',
    'd de sousa britto':        'daniel',
    'j klauss':                 'klauss',
    'j mior':                   'joao paulo',
    'p martins':                'pedrinho',
    'k ferreira':               'j ferreira',
    'm dos santos silva':       'micael',
    'r benetti':                'ramiro',
    'r gregorio teixeira':      'ruan',
    'l diaz espinoza':          'l diaz',
    'j klein iii':              'j klein',
}

# Genuinely not in DB — need scraping:
# r cabral (RSL), s suleymanov (SKC), k kim (SEA), j reginaldo (CLT),
# m cafumana (DAL), n pelae cardoso (SEA), c olivares (STL),
# a oyirwoth (NE), j berrocal (ATL), l deedson (DAL),
# w abou ali (CLB), b farkarlun (ATX), g dillon (RSL),
# s lapkes (CLB), b souza (CIN), j dilrosun (LAFC),
# m oneill (VAN), v costa de brito (SJ), d konincks (CHI),
# m kerkvliet (RSL), l frugis afonso (MIA)

In [171]:
# Apply manual map to name_norm before lookup
match_players['name_lookup'] = match_players['name_norm'].replace(PLAYER_NAME_MAP)

# Re-run lookup on still-unmatched
name_id_lookup = players.drop_duplicates(subset='name_norm').set_index('name_norm')['id']

mask = match_players['player_id'].isna()
match_players.loc[mask, 'player_id'] = match_players.loc[mask, 'name_lookup'].map(name_id_lookup)

print("Still unmatched:", match_players['player_id'].isna().sum())
print("Unique unmatched:", match_players[match_players['player_id'].isna()]['player_name'].nunique())

Still unmatched: 625
Unique unmatched: 151

In [172]:
# Check if the map is actually replacing values
test = match_players[match_players['name_norm'].isin(PLAYER_NAME_MAP.keys())][['player_name', 'name_norm', 'name_lookup', 'player_id']].head(20)
print(test)

               player_name            name_norm name_lookup  player_id
30    E. Da Silva Ferreira  e da silva ferreira     evander   234505.0
67         A. Alves Santos       a alves santos      antony   263947.0
417     D. De Sousa Britto    d de sousa britto      daniel   238604.0
463              J. Klauss             j klauss      klauss   242998.0
527             R. Benetti            r benetti      ramiro   215643.0
530            K. Ferreira           k ferreira  j ferreira   241487.0
599              J. Klauss             j klauss      klauss   242998.0
624        A. Alves Santos       a alves santos      antony   263947.0
664             R. Benetti            r benetti      ramiro   215643.0
667            K. Ferreira           k ferreira  j ferreira   241487.0
724   E. Da Silva Ferreira  e da silva ferreira     evander   234505.0
774     D. De Sousa Britto    d de sousa britto      daniel   238604.0
943        A. Alves Santos       a alves santos      antony   263947.0
961              J. Klauss             j klauss      klauss   242998.0
1025  E. Da Silva Ferreira  e da silva ferreira     evander   234505.0
1231               J. Mior               j mior  joao paulo        NaN
1329            P. Martins            p martins    pedrinho    77657.0
1336            R. Benetti            r benetti      ramiro   215643.0
1339           K. Ferreira           k ferreira  j ferreira   241487.0
1423              J. Artur              j artur       artur   234122.0

In [173]:
# Check if the mapped names exist in the lookup
for orig, mapped in PLAYER_NAME_MAP.items():
    mapped_norm = norm(mapped)
    in_lookup = mapped_norm in name_id_lookup.index
    print(f"{orig} → {mapped_norm} → in lookup: {in_lookup}")

a alves santos → antony → in lookup: True
e da silva ferreira → evander → in lookup: True
a rodrigues de oliveira → rodrigues → in lookup: True
c carrasquilla → a carrasquilla → in lookup: True
y gomez → y gomez andrade → in lookup: True
j artur → artur → in lookup: True
j de lima junior → artur → in lookup: True
d de sousa britto → daniel → in lookup: True
j klauss → klauss → in lookup: True
j mior → j paulo → in lookup: True
p martins → pedrinho → in lookup: True
k ferreira → j ferreira → in lookup: True
m dos santos silva → micael → in lookup: True
r benetti → ramiro → in lookup: True
r gregorio teixeira → ruan → in lookup: True
l diaz espinoza → l diaz → in lookup: True
j klein iii → j klein → in lookup: True

In [93]:
### change first name to first intial if not already


players['name_norm'] = (
    players['name_norm']
    .str.lower()
    .str.strip()
    .apply(lambda x: x[0] + '. ' + ' '.join(x.split(' ')[1:]) if isinstance(x, str) and ' ' in x else x)
)

match_players2 = match_players.copy()

match_players2['name_norm'] = (
    match_players2['name_norm']
    .str.lower()
    .str.strip()
    .apply(lambda x: x[0] + '. ' + ' '.join(x.split(' ')[1:]) if isinstance(x, str) and ' ' in x else x)
)

In [94]:
players['date'] = pd.to_datetime(players['date'])
match_players2['date'] = pd.to_datetime(match_players2['date'])

# Merge on name only — will create cartesian product of all snapshots per player
df = match_players2.merge(
    players[['id', 'name_norm', 'date']],
    left_on='name_norm',
    right_on='name_norm',
    how='left',
    suffixes=('_match', '_player')
)

# Drop snapshots AFTER the match date
df = df[df['date_player'] <= df['date_match']]

# Keep only the closest snapshot before the match
df = (df.sort_values('date_player', ascending=False)
        .drop_duplicates(subset=['match_id', 'name_norm'], keep='first'))

# Clean up
df = df.drop(columns=['name_norm', 'date_player'])
df = df.rename(columns={'date_match': 'date', 'id': 'player_id'})

print("Matched:", df['player_id'].notna().sum())
print("Unmatched:", df['player_id'].isna().sum())

Matched: 38585
Unmatched: 0

In [95]:
# Create a lookup Series: player_name + match_id -> player_id
id_lookup = df.set_index(['match_id', 'player_name'])['player_id']

# Map back to original
match_players2['player_id'] = match_players2.set_index(['match_id', 'player_name']).index.map(id_lookup)

print("Matched:", match_players2['player_id'].notna().sum())
print("Unmatched:", match_players2['player_id'].isna().sum())

Matched: 38612
Unmatched: 2811

In [96]:
# See examples of unmatched names
unmatched = match_players2[match_players2['player_id'].isna()]['player_name'].unique()
print("Sample unmatched:", unmatched[:20])

# Compare with players table names
matched = match_players2[match_players2['player_id'].notna()]['player_name'].unique()
print("Sample matched:", matched[:10])

# Check players table name format
print("Players table names:", players['name'].unique()[:20])

Sample unmatched: ['T. Rosborough' 'J. Ruvalcaba' 'A. Mehmeti' 'M. Dos Santos' 'E. Horvath'
 'E. Da Silva Ferreira' 'B. Ramírez' 'G. Sequera' 'S. Korzeniowski'
 'C. Sullivan' 'E. Alladoh' 'J. Sery Larsen' 'A. Anello' 'A. Alves Santos'
 'E. Izoita' 'C. Ondo' 'A. Aravena' 'W. Madrigal' 'M. Woledzi'
 'D. Polvara']
Sample matched: ['T. Parker' 'J. McCarthy' 'C. Cowell' 'R. Voloder' 'J. Marshall-Rutty'
 'J. Che' 'O. Valencia' 'J. Hall' 'R. Mosquera' 'J. Mina']
Players table names: ['j. maurer' 'r. cannon' 'm. hedges' 'r. ziegler' 'm. figueroa' 'j. hayes'
 'c. gruezo' 'm. barrios' 'r. lamah' 'm. diaz' 'm. urruti' 'c. colman'
 't. akindele' 's. mosquera' 'v. ulloa' 'r. hollingshead' 'a. nedyalkov'
 'j. gonzalez' 'k. acosta' 'p. pomykal']

In [97]:
# Check if unmatched names exist anywhere in players table at all (ignore date)
unmatched_names = match_players2[match_players2['player_id'].isna()]['player_name'].unique()

found_in_players = players[players['name'].isin(unmatched_names)]['name'].unique()
not_in_players_at_all = [n for n in unmatched_names if n not in found_in_players]

print(f"Unmatched due to date filter: {len(found_in_players)}")
print(f"Not in players table at all: {len(not_in_players_at_all)}")
print("\nSample missing entirely:", not_in_players_at_all[:10])

Unmatched due to date filter: 0
Not in players table at all: 453

Sample missing entirely: ['T. Rosborough', 'J. Ruvalcaba', 'A. Mehmeti', 'M. Dos Santos', 'E. Horvath', 'E. Da Silva Ferreira', 'B. Ramírez', 'G. Sequera', 'S. Korzeniowski', 'C. Sullivan']

In [98]:
# Re-merge but allow any date
df_all = match_players2.merge(
    players[['id', 'name', 'date']],
    left_on='player_name',
    right_on='name',
    how='left',
    suffixes=('_match', '_player')
)

# Get closest snapshot in either direction
df_all['date_diff'] = (df_all['date_player'] - df_all['date_match']).abs()
df_all = (df_all.sort_values('date_diff')
                .drop_duplicates(subset=['match_id', 'player_name'], keep='first'))

id_lookup_all = df_all.set_index(['match_id', 'player_name'])['id']

# Only fill the still-unmatched rows
mask = match_players2['player_id'].isna()
match_players2.loc[mask, 'player_id'] = (
    match_players2[mask]
    .set_index(['match_id', 'player_name'])
    .index.map(id_lookup_all)
)

print("Still unmatched:", match_players2['player_id'].isna().sum())

Still unmatched: 2811

In [99]:
# Check if the 200 date-filtered ones got matched
found_in_players = players[players['name'].isin(unmatched_names)]['name'].unique()

still_unmatched = match_players2[match_players2['player_id'].isna()]['player_name'].unique()

# How many of the 200 are still unmatched?
still_from_200 = [n for n in still_unmatched if n in found_in_players]
print("From the 200 still unmatched:", len(still_from_200))

# How many are the 344 missing entirely?
still_from_344 = [n for n in still_unmatched if n not in found_in_players]
print("From the 344 still unmatched:", len(still_from_344))

# Sanity check — did player_id get overwritten somehow?
print("\nTotal unmatched rows:", match_players2['player_id'].isna().sum())
print("Total rows:", len(match_players2))

From the 200 still unmatched: 0
From the 344 still unmatched: 453

Total unmatched rows: 2811
Total rows: 41423

In [100]:
print("Non-null player_ids:", match_players2['player_id'].notna().sum())

Non-null player_ids: 38612

In [101]:
missing_players = (match_players2[match_players2['player_id'].isna()]['player_name']
                   .unique())

pd.Series(missing_players, name='player_name').to_csv('missing_players.csv', index=False)
print(f"{len(missing_players)} players need scraping")

453 players need scraping

In [103]:
sql_df['name'] = (
    sql_df['name']
    .str.lower()
    .str.strip()
    .apply(lambda x: x[0] + '. ' + ' '.join(x.split(' ')[1:]) if isinstance(x, str) and ' ' in x else x)
)

sql_df['name_norm'] = sql_df['name'].apply(norm)

In [104]:
# Drop duplicate names keeping first occurrence
name_id_lookup = sql_df.drop_duplicates(subset='name_norm').set_index('name_norm')['player_id']

mask = match_players2['player_id'].isna()
match_players2.loc[mask, 'player_id'] = (
    match_players2.loc[mask, 'name_norm'].map(name_id_lookup)
)

print("Still unmatched:", match_players2['player_id'].isna().sum())
print("Unique unmatched players:", match_players2[match_players2['player_id'].isna()]['name_norm'].nunique())

Still unmatched: 2811
Unique unmatched players: 449

In [105]:
still_unmatched = match_players2[match_players2['player_id'].isna()]['player_name'].unique()

# Check if they exist in name_id_df under a different format
sample = still_unmatched[:20]
for name in sample:
    # Try to find similar names
    last_name = name.split('.')[-1].strip()
    matches = sql_df[sql_df['name'].str.contains(last_name, case=False, na=False)]['name'].values
    if len(matches) > 0:
        print(f"{name} → possible match: {matches}")

J. Ruvalcaba → possible match: ['c. ruvalcaba']
M. Dos Santos → possible match: ['g. dos santos' 'j. dos santos' 'c. dos santos']
C. Sullivan → possible match: ['q. sullivan']
A. Anello → possible match: ['j. rafanello']
C. Ondo → possible match: ['c. wondolowski' 'j. diraimondo' 's. wondolowski' 'f. redondo']

In [68]:
# Document what's missing for later scraping
missing_final = (match_players2[match_players2['player_id'].isna()][['player_name', 'club']]
                 .drop_duplicates()
                 .sort_values('player_name'))

missing_final.to_csv('missing_players_final.csv', index=False)
print(f"Saving {len(missing_final)} unmatched player/club combos for later scraping")

# Summary of where we landed
total = len(match_players2)
matched = match_players2['player_id'].notna().sum()
print(f"\nMatched: {matched}/{total} rows ({matched/total*100:.1f}%)")

Saving 310 unmatched player/club combos for later scraping

Matched: 36874/41423 rows (89.0%)

In [69]:
### show dates of unmatched players to see if there's a pattern

match_players2[match_players2['player_id'].isna()][['player_name', 'date']].drop_duplicates().sort_values('date')

           player_name       date
41416         a. gómez 2024-02-21
20726        t. avilés 2024-02-21
20727        l. suárez 2024-02-21
20725         d. gómez 2024-02-21
20638      j. martínez 2024-02-24
...                ...        ...
20747        n. streit 2026-03-08
20737  d. thórhallsson 2026-03-08
20731          d. ríos 2026-03-08
20767   e. aristizábal 2026-03-08
9         j. ruvalcaba 2026-03-08

[4504 rows x 2 columns]

In [135]:
### create a player dictionary to map player names to player ids by lowering case and stripping whitespace

def norm(s):
    if pd.isna(s):
        return ""
    return (
        str(s).lower()
        .replace(".", "")
        .replace("-", " ")
        .replace("'", "")
        .strip()
    )

mp = match_players.copy()
pl = players.copy()

mp["name_norm"] = mp["player_name"].apply(norm)
mp["club"] = mp["club"].apply(norm)

pl["name_norm"] = pl["name"].apply(norm)
pl["team_abbr"] = pl["team_abbr"].apply(norm)

In [136]:
### keep first occurrence of each player name and club combination in players dataframe to create a mapping of player name and club to player id by date

pl_deduped = pl.drop_duplicates(subset=['name_norm', 'team_abbr', 'date'], keep='first')

In [139]:
### rename team_abbr col

pl_deduped = pl_deduped.rename(columns={'team_abbr': 'club_norm'})

In [140]:
mp = mp.rename(columns={'club': 'club_norm'})

In [143]:
### do all club + name exact matches first and then fuzzy match the rest to get player ids for match players stats

merged = mp.merge(pl_deduped[['id', 'name_norm', 'club_norm']], on=['name_norm', 'club_norm'], how='left')

In [144]:
merged

         match_id        date player_name  minutes  goals  expected_goals  shot_conv_perc  on_target  pass_perc  assists  passes  cross  corner_kick  key_pass  aerial  aerial_perc  fouls  fouls_against  offside  yellow_card  red_card  side  goals_saved  goals_against  expected_goals_against  Pass  gk_throws  gk_long_balls  gk_launches   GK  corners_conceded club_norm  name_norm        id
0        c1d67317  2026-03-08   T. Parker        0      0             0.0             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny   t parker  226803.0
1        c1d67317  2026-03-08   T. Parker        0      0             0.0             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny   t parker  226803.0
2        c1d67317  2026-03-08   T. Parker        0      0             0.0             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny   t parker  226803.0
3        c1d67317  2026-03-08   T. Parker        0      0             0.0             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny   t parker  226803.0
4        c1d67317  2026-03-08   T. Parker        0      0             0.0             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny   t parker  226803.0
...           ...         ...         ...      ...    ...             ...             ...        ...        ...      ...     ...    ...          ...       ...     ...          ...    ...            ...      ...          ...       ...   ...          ...            ...                     ...   ...        ...            ...          ...  ...               ...       ...        ...       ...
4739336  91a639d5  2024-02-21  Z. MacMath       90      6             0.0             NaN        NaN        NaN        0       0      0          NaN       NaN     NaN          NaN    NaN              0        0          NaN         0  away          2.0            0.0                    25.0  75.8        9.0            0.0          0.0  0.0               0.0       rsl  z macmath  201940.0
4739337  91a639d5  2024-02-21  Z. MacMath       90      6             0.0             NaN        NaN        NaN        0       0      0          NaN       NaN     NaN          NaN    NaN              0        0          NaN         0  away          2.0            0.0                    25.0  75.8        9.0            0.0          0.0  0.0               0.0       rsl  z macmath  201940.0
4739338  91a639d5  2024-02-21  Z. MacMath       90      6             0.0             NaN        NaN        NaN        0       0      0          NaN       NaN     NaN          NaN    NaN              0        0          NaN         0  away          2.0            0.0                    25.0  75.8        9.0            0.0          0.0  0.0               0.0       rsl  z macmath  201940.0
4739339  91a639d5  2024-02-21  Z. MacMath       90      6             0.0             NaN        NaN        NaN        0       0      0          NaN       NaN     NaN          NaN    NaN              0        0          NaN         0  away          2.0            0.0                    25.0  75.8        9.0            0.0          0.0  0.0               0.0       rsl  z macmath  201940.0
4739340  91a639d5  2024-02-21  Z. MacMath       90      6             0.0             NaN        NaN        NaN        0       0      0          NaN       NaN     NaN          NaN    NaN              0        0          NaN         0  away          2.0            0.0                    25.0  75.8        9.0            0.0          0.0  0.0               0.0       rsl  z macmath  201940.0

[4739341 rows x 34 columns]

In [153]:
### how many times did we get a match on player name and club?


key_cols = ['match_id', 'name_norm']

dupes = merged[merged.duplicated(subset=key_cols, keep=False)]
print("Total duplicated rows:", len(dupes))
print("\nHow many times each combo appears:")
print(merged.groupby(key_cols).size().reset_index(name='count').sort_values('count', ascending=False).head(20))

Total duplicated rows: 4732780

How many times each combo appears:
       match_id  name_norm  count
35314  dac9d054  a farrell    802
14359  5bd48883  a farrell    802
39468  f5e2531a  a farrell    802
18641  73b1eb8f  a farrell    802
20143  7be88247  a farrell    802
32057  c8e6bb8a  a farrell    802
29063  b66207fb  a farrell    802
36186  e09fca0b  a farrell    802
19198  762f4021  a farrell    802
38992  f3844516  a farrell    802
24967  9d9f1ac3  a farrell    802
5024   1dfcb822  a farrell    802
3767   16d6a453  a farrell    802
39783  f7019627  a farrell    802
2335   0e25803e  a farrell    802
13328  576f6f04  a farrell    802
17772  6d20027c  a farrell    802
3207   12769fea  a farrell    802
5817   245c0550  a farrell    802
7599   3230992f  a farrell    802

In [154]:
### keep only first instance of each name_norm and match_id combination to avoid duplicates

merged_deduped = merged.drop_duplicates(subset=['match_id', 'name_norm'], keep='first')

merged_deduped

         match_id        date        player_name  minutes  goals  expected_goals  shot_conv_perc  on_target  pass_perc  assists  passes  cross  corner_kick  key_pass  aerial  aerial_perc  fouls  fouls_against  offside  yellow_card  red_card  side  goals_saved  goals_against  expected_goals_against  Pass  gk_throws  gk_long_balls  gk_launches   GK  corners_conceded club_norm         name_norm        id
0        c1d67317  2026-03-08          T. Parker        0      0            0.00             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny          t parker  226803.0
233      c1d67317  2026-03-08        J. McCarthy        0      0            0.00             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny        j mccarthy  227909.0
251      c1d67317  2026-03-08          C. Cowell       85      0            0.06             1.0        1.0       65.7        0      23      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny          c cowell       NaN
252      c1d67317  2026-03-08         R. Voloder       90      0            0.04             1.0        0.0       92.1        0      58      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny         r voloder  256499.0
256      c1d67317  2026-03-08  J. Marshall-Rutty       77      0            0.02             1.0        0.0       94.6        0      53      0          0.0       0.0     0.0          0.0    1.0              1        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny  j marshall rutty       NaN
...           ...         ...                ...      ...    ...             ...             ...        ...        ...      ...     ...    ...          ...       ...     ...          ...    ...            ...      ...          ...       ...   ...          ...            ...                     ...   ...        ...            ...          ...  ...               ...       ...               ...       ...
4738708  91a639d5  2024-02-21        N. Caliskan       17      0            0.00             0.0        0.0       88.2        0      15      0          0.0       0.0     0.0          0.0    0.0              1        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN       rsl        n caliskan  275645.0
4738773  91a639d5  2024-02-21         F. Barajas       24      0            0.00             0.0        0.0       81.8        0       9      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN       rsl         f barajas   70857.0
4738785  91a639d5  2024-02-21           E. Eneli       90      0            0.00             0.0        0.0       93.3        0      42      0          0.0       0.0     0.0          0.0    0.0              1        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN       rsl           e eneli  274970.0
4738921  91a639d5  2024-02-21         N. Palacio       66      0            0.02             1.0        0.0       92.0        0      46      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN       rsl         n palacio  264433.0
4739018  91a639d5  2024-02-21         Z. MacMath       90      6            0.00             NaN        NaN        NaN        0       0      0          NaN       NaN     NaN          NaN    NaN              0        0          NaN         0  away          2.0            0.0                    25.0  75.8        9.0            0.0          0.0  0.0               0.0       rsl         z macmath  201940.0

[41396 rows x 34 columns]

In [155]:
merged_deduped['name'] = merged_deduped['name_norm']

C:\Users\diffe\AppData\Local\Temp\ipykernel_14652\1475804238.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_deduped['name'] = merged_deduped['name_norm']

In [159]:
merged_deduped = merged_deduped.rename(columns={'id': 'player_id'})

In [183]:
### find nan player_id in merged

merged_deduped['player_id'].isna().sum()

1735

In [184]:
### subset pl to only after 01/01/24

pl_deduped['date'] = pd.to_datetime(pl_deduped['date'], errors='coerce')

pl_deduped = pl_deduped[pl_deduped['date'] >= '2024-01-01']

In [208]:
from rapidfuzz import process, fuzz

unmatched = mp[mp["player_id"].isna()].copy()

# build lookup: club -> list of (name_norm, id)
club_lookup = {}
for club, sub in pl_deduped.groupby("club_norm"):
    club_lookup[club] = list(zip(sub["name_norm"].tolist(), sub["id"].tolist()))


# 1) clubs in match_players that don't exist in players (after normalization)
missing_clubs = sorted(set(unmatched["club_norm"]) - set(club_lookup.keys()))
print("Missing clubs count:", len(missing_clubs))
print(missing_clubs[:30])

# 2) how many unmatched rows are missing because club had zero candidates
unmatched["club_has_choices"] = unmatched["club_norm"].map(lambda c: c in club_lookup)
print(unmatched["club_has_choices"].value_counts(dropna=False))

# initialize fuzzy_score column in merged if it doesn't exist
if "fuzzy_score" not in merged_deduped.columns:
    merged_deduped["fuzzy_score"] = None

Missing clubs count: 0
[]
club_has_choices
True    732
Name: count, dtype: int64

In [209]:
def fuzzy_find(row, cutoff=70):
    club = row["club_norm"]
    name = row["name_norm"]
    choices = club_lookup.get(club, [])
    if not choices:
        return pd.Series([None, 0])

    names = [x[0] for x in choices]
    best = process.extractOne(name, names, scorer=fuzz.token_sort_ratio)
    if best is None:
        return pd.Series([None, 0])

    _, score, idx = best
    if score < cutoff:
        return pd.Series([None, score])

    return pd.Series([choices[idx][1], score])

unmatched[["player_id_fuzzy", "fuzzy_score"]] = unmatched.apply(fuzzy_find, axis=1)

In [210]:
# fill missing ids with fuzzy results
mp.loc[
    unmatched.index, "player_id"
] = unmatched["player_id_fuzzy"]

mp.loc[
    unmatched.index, "fuzzy_score"
] = unmatched["fuzzy_score"]

In [211]:
mp.isna().sum()

match_id                      0
date                          0
player_name                   0
minutes                       0
goals                         0
expected_goals                0
shot_conv_perc             2123
on_target                  2123
pass_perc                  2123
assists                       0
passes                        0
cross                         0
corner_kick                2123
key_pass                   2123
aerial                     2123
aerial_perc                2123
fouls                      2123
fouls_against                 0
offside                       0
yellow_card                2123
red_card                      0
side                          0
goals_saved               39302
goals_against             39300
expected_goals_against    39300
Pass                      39300
gk_throws                 39300
gk_long_balls             39300
gk_launches               39300
GK                        39300
corners_conceded          39300
club_norm                     0
name_norm                     0
player_id                   692
fuzzy_score_name              0
fuzzy_score               40691
dtype: int64

In [190]:
sql_df['name'] = sql_df['name'].apply(norm)

sql_df = sql_df.rename(columns={"player_name": "name"})

In [206]:
from rapidfuzz import process, fuzz

mp['player_id'] = None

unmatched2 = mp.copy()

# build lookup: name -> player_id

name_lookup = dict(zip(sql_df["name"], sql_df["player_id"]))

def fuzzy_find_name(row, cutoff=70):
    name = row["name_norm"]
    choices = list(name_lookup.keys())
    best = process.extractOne(name, choices, scorer=fuzz.token_sort_ratio)
    if best is None:
        return pd.Series([None, 0])

    _, score, idx = best
    if score < cutoff:
        return pd.Series([None, score])

    return pd.Series([name_lookup[choices[idx]], score])    

unmatched2[["player_id_fuzzy_name", "fuzzy_score_name"]] = unmatched2.apply(fuzzy_find_name, axis=1)

match_id                      0
date                          0
player_name                   0
minutes                       0
goals                         0
expected_goals                0
shot_conv_perc             2123
on_target                  2123
pass_perc                  2123
assists                       0
passes                        0
cross                         0
corner_kick                2123
key_pass                   2123
aerial                     2123
aerial_perc                2123
fouls                      2123
fouls_against                 0
offside                       0
yellow_card                2123
red_card                      0
side                          0
goals_saved               39302
goals_against             39300
expected_goals_against    39300
Pass                      39300
gk_throws                 39300
gk_long_balls             39300
gk_launches               39300
GK                        39300
corners_conceded          39300
club_norm                     0
name_norm                     0
player_id                   732
fuzzy_score_name              0
dtype: int64

In [207]:
# fill missing ids with fuzzy results
mp.loc[
    unmatched2.index, "player_id"
] = unmatched2["player_id_fuzzy_name"]

mp.loc[
    unmatched2.index, "fuzzy_score_name"
] = unmatched2["fuzzy_score_name"]


mp.isna().sum()

match_id                      0
date                          0
player_name                   0
minutes                       0
goals                         0
expected_goals                0
shot_conv_perc             2123
on_target                  2123
pass_perc                  2123
assists                       0
passes                        0
cross                         0
corner_kick                2123
key_pass                   2123
aerial                     2123
aerial_perc                2123
fouls                      2123
fouls_against                 0
offside                       0
yellow_card                2123
red_card                      0
side                          0
goals_saved               39302
goals_against             39300
expected_goals_against    39300
Pass                      39300
gk_throws                 39300
gk_long_balls             39300
gk_launches               39300
GK                        39300
corners_conceded          39300
club_norm                     0
name_norm                     0
player_id                   732
fuzzy_score_name              0
dtype: int64

In [193]:
merged_deduped

         match_id        date        player_name  minutes  goals  expected_goals  shot_conv_perc  on_target  pass_perc  assists  passes  cross  corner_kick  key_pass  aerial  aerial_perc  fouls  fouls_against  offside  yellow_card  red_card  side  goals_saved  goals_against  expected_goals_against  Pass  gk_throws  gk_long_balls  gk_launches   GK  corners_conceded club_norm         name_norm  player_id              name  fuzzy_score  fuzzy_score_name
0        c1d67317  2026-03-08          T. Parker        0      0            0.00             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny          t parker   226803.0          t parker          NaN               NaN
233      c1d67317  2026-03-08        J. McCarthy        0      0            0.00             0.0        0.0        0.0        0       0      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny        j mccarthy   227909.0        j mccarthy          NaN               NaN
251      c1d67317  2026-03-08          C. Cowell       85      0            0.06             1.0        1.0       65.7        0      23      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny          c cowell   242084.0          c cowell    70.588235               NaN
252      c1d67317  2026-03-08         R. Voloder       90      0            0.04             1.0        0.0       92.1        0      58      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny         r voloder   256499.0         r voloder          NaN               NaN
256      c1d67317  2026-03-08  J. Marshall-Rutty       77      0            0.02             1.0        0.0       94.6        0      53      0          0.0       0.0     0.0          0.0    1.0              1        0          0.0         0  home          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN      rbny  j marshall rutty   255335.0  j marshall rutty    53.846154             100.0
...           ...         ...                ...      ...    ...             ...             ...        ...        ...      ...     ...    ...          ...       ...     ...          ...    ...            ...      ...          ...       ...   ...          ...            ...                     ...   ...        ...            ...          ...  ...               ...       ...               ...        ...               ...          ...               ...
4738708  91a639d5  2024-02-21        N. Caliskan       17      0            0.00             0.0        0.0       88.2        0      15      0          0.0       0.0     0.0          0.0    0.0              1        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN       rsl        n caliskan   275645.0        n caliskan          NaN               NaN
4738773  91a639d5  2024-02-21         F. Barajas       24      0            0.00             0.0        0.0       81.8        0       9      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN       rsl         f barajas    70857.0         f barajas          NaN               NaN
4738785  91a639d5  2024-02-21           E. Eneli       90      0            0.00             0.0        0.0       93.3        0      42      0          0.0       0.0     0.0          0.0    0.0              1        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN       rsl           e eneli   274970.0           e eneli          NaN               NaN
4738921  91a639d5  2024-02-21         N. Palacio       66      0            0.02             1.0        0.0       92.0        0      46      0          0.0       0.0     0.0          0.0    0.0              0        0          0.0         0  away          NaN            NaN                     NaN   NaN        NaN            NaN          NaN  NaN               NaN       rsl         n palacio   264433.0         n palacio          NaN               NaN
4739018  91a639d5  2024-02-21         Z. MacMath       90      6            0.00             NaN        NaN        NaN        0       0      0          NaN       NaN     NaN          NaN    NaN              0        0          NaN         0  away          2.0            0.0                    25.0  75.8        9.0            0.0          0.0  0.0               0.0       rsl         z macmath   201940.0         z macmath          NaN               NaN

[41396 rows x 37 columns]

In [194]:
### check for match_id, player_id duplicates

dupes = merged_deduped[merged_deduped.duplicated(subset=['match_id', 'player_name'], keep=False)].sort_values(by=['match_id', 'player_name'])

dupes

Empty DataFrame
Columns: [match_id, date, player_name, minutes, goals, expected_goals, shot_conv_perc, on_target, pass_perc, assists, passes, cross, corner_kick, key_pass, aerial, aerial_perc, fouls, fouls_against, offside, yellow_card, red_card, side, goals_saved, goals_against, expected_goals_against, Pass, gk_throws, gk_long_balls, gk_launches, GK, corners_conceded, club_norm, name_norm, player_id, name, fuzzy_score, fuzzy_score_name]
Index: []

In [202]:
### compare merged_deduped and sql_df names that have no id yet

unmatched_names = merged_deduped[merged_deduped["player_id"].isna()]["name_norm"].unique()

unmatched_names

array(['t rosborough', 'a mehmeti', 'e da silva ferreira',
       's korzeniowski', 'j sery larsen', 'e izoita', 'w madrigal',
       'm woledzi', 'l munteanu', 'k kurokawa', 't calheira',
       'z loyo reynaga', 't jacob', 'e báez', 'l hoyos', 's eustáquio',
       'o presthus', 'z taifi', 'i da silva nogueira', 'l otávio',
       'b zamblé', 'a salétros', 'm mbokazi', 'd de sousa britto',
       'm gherasimencov', 'g pec', 'a hezarkhani', 'z booth',
       'm guilavogui', 'r benetti', 'r binyamin', 'n adimabua',
       'g diarbian', 'á roldán', 'r montenegro', 'a băluță',
       'j marques siqueira', 'k chandler', 'a rodrigues de oliveira',
       'm kerkvliet', 'n fernández mercau', 'c abadia reda', 't ángel',
       'j santiago', 'é díaz', 'l chú', 'j de lima júnior', 'w speel',
       'a coupland', 'v hlyut', 'j shokalook', 'j selemani', 'l ulrich',
       'h karamoko', 'd konincks', 'k rizvanovich', 'j de lima junior',
       's lapkes', 'k linhares', 'n pelae cardoso', 'r gregório teixeira',
       'e berumen', 'v enriquez velazquez', 'd iskenderian',
       'c staniland', 'v costa de brito', 'h ayari', 'k romanshyn',
       'l frugis afonso', 'a dumitru', 'j casas de abadal', 'q ordoñez',
       'b kuscevic', 'e aristizábal', 's spierings', 'a shaw', 't majub',
       'f sundstrom', 's mazzaferro', 'e jääskeläinen', 'c kachwele',
       'r odriscoll', 'f mcrobb', 't clegg', 'j arroyave', 'g delibera',
       'v noël'], dtype=object)

In [103]:
### keep first occurrence of each match_id and player_name combination in clean to get unique match id and player name combinations where player_id is not null

clean_unique = clean.drop_duplicates(subset=['match_id', 'player_name'], keep='first')

In [104]:
clean_unique

,match_id,date_x,player_name,minutes,goals,expected_goals,shot_conv_perc,on_target,pass_perc,assists,passes,cross,corner_kick,key_pass,aerial,aerial_perc,fouls,fouls_against,offside,yellow_card,red_card,side,goals_saved,goals_against,expected_goals_against,Pass,gk_throws,gk_long_balls,gk_launches,GK,corners_conceded,club,name_norm,club_norm,date_y,name,age,height_cm,weight_kg,team_name,contract_start,contract_end,position,foot,jersey_num,wage_eur,value_eur,overall_rating,best_overall,best_position,total_attacking,crossing,finishing,heading_accuracy,short_passing,volleys,total_skill,dribbling,curve,fk_accuracy,long_passing,ball_control,total_movement,acceleration,sprint_speed,agility,reactions,balance,total_power,shot_power,jumping,stamina,long_shots,total_mentality,aggression,interceptions,attack_position,vision,penalties,composure,total_defending,defensive_awareness,standing_tackle,sliding_tackle,total_goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,team_abbr,fuzzy_score,player_id
0,c1d67317,2026-03-08,T. Parker,0,0,0.00,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbny,t parker,rbny,2025-07-17,t parker,31.0,188.0,88.0,NaN,2025.0,2025.0,SUB,Right,26.0,6000.0,700000.0,67.0,67.0,CB,218.0,26.0,35.0,70.0,59.0,28.0,206.0,43.0,21.0,26.0,57.0,59.0,283.0,62.0,68.0,46.0,64.0,43.0,288.0,33.0,80.0,69.0,21.0,239.0,75.0,64.0,28.0,35.0,37.0,60.0,191.0,64.0,64.0,63.0,51.0,6.0,13.0,14.0,9.0,9.0,rbny,NaN,226803.0
1,c1d67317,2026-03-08,J. McCarthy,0,0,0.00,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbny,j mccarthy,rbny,2025-09-19,j mccarthy,32.0,185.0,84.0,NaN,2025.0,2025.0,RES,Right,23.0,3000.0,600000.0,68.0,68.0,GK,93.0,17.0,17.0,17.0,24.0,18.0,64.0,10.0,15.0,13.0,14.0,12.0,202.0,35.0,34.0,36.0,57.0,40.0,214.0,44.0,59.0,38.0,13.0,106.0,32.0,19.0,19.0,18.0,18.0,44.0,42.0,14.0,13.0,15.0,331.0,69.0,69.0,58.0,65.0,70.0,rbny,NaN,227909.0
3,c1d67317,2026-03-08,R. Voloder,90,0,0.04,1.0,0.0,92.1,0,58,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbny,r voloder,rbny,2026-02-05,r voloder,24.0,185.0,75.0,NaN,2026.0,2026.0,LCB,Left,18.0,2000.0,550000.0,62.0,64.0,CB,194.0,32.0,23.0,56.0,56.0,27.0,208.0,49.0,29.0,25.0,50.0,55.0,301.0,63.0,69.0,56.0,55.0,58.0,256.0,42.0,66.0,59.0,20.0,215.0,50.0,62.0,28.0,35.0,40.0,52.0,194.0,63.0,66.0,65.0,59.0,12.0,10.0,8.0,14.0,15.0,rbny,NaN,256499.0
4,c1d67317,2026-03-08,J. Marshall-Rutty,77,0,0.02,1.0,0.0,94.6,0,53,0,0.0,0.0,0.0,0.0,1.0,1,0,0.0,0,home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbny,j marshall rutty,rbny,NaN,j marshall rutty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.846154,255335.0
5,c1d67317,2026-03-08,J. Che,90,0,0.00,0.0,0.0,88.6,0,70,0,0.0,0.0,0.0,0.0,2.0,1,0,1.0,0,home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbny,j che,rbny,NaN,j che,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.142857,259159.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43456,91a639d5,2024-02-21,N. Caliskan,17,0,0.00,0.0,0.0,88.2,0,15,0,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0,away,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rsl,n caliskan,rsl,2024-03-20,n caliskan,22.0,180.0,68.0,NaN,2024.0,2024.0,RES,Right,92.0,1000.0,210000.0,53.0,56.0,CDM,224.0,42.0,39.0,44.0,58.0,41.0,249.0,52.0,47.0,39.0,55.0,56.0,295.0,57.0,60.0,60.0,54.0,64.0,233.0,52.0,43.0,52.0,32.0,243.0,62.0,49.0,40.0,52.0,40.0,49.0,151.0,46.0,60.0,45.0,61.0,9.0,11.0,13.0,14.0,14.0,rsl,NaN,275645.0
43457,91a639d5,2024-02-21,F. Barajas,24,0,0.00,0.0,0.0,81.8,0,9,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,away,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rsl,f barajas,rsl,2024-04-23,f barajas,17.0,175.0,68.0,NaN,2024.0,2026.0,RES,Left,17.0,500.0,150000.0,50.0,51.0,LM,212.0,47.0,45.0,33.0,46.0,41.0,215.0,48.0,40.0,34.0,41.0,52.0,297.0,69.0,66.0,65.0,35.0,62.0,212.0,50.0,33.0,50.0,39.0,204.0,40.0,19.0,47.0,48.0,50.0,49.0,74.0,24.0,29.0,21.0,49.0,11.0,10.0,11.0,8.0,9.0,rsl,NaN,70857.0
43458,91a639d5,2024-02-21,E. Eneli,90,0,0.00,0.0,0.0,93.3,0,42,0,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0,away,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rsl,e eneli,rsl,2023-05-26,e eneli,22.0,175.0,70.0,NaN,2023.0,2023.0,SUB,Right,25.0,1000.0,190000.0,55.0,55.0,RB,239.0,44.0,46.0,45.0,62.0,42.0,231.0,47.0,43.0,34.0,58.0,49.0,324.0,70.0,65.0,65.0,47.0,77.0,281.0,45.0,69.0,69.0,44.0,239.0,51.0,48.0,50.0,50.0,40.0,36.0,145.0,48.0,51.0,46.0,50.0,11.0,11.0,13.0,10.0,5.0,rsl,NaN,274970.0
43459,91a639d5,2024-02-21,N. Palacio,66,0,0.02,1.0,0.0,92.0,0,46,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,away,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rsl,n palacio,rsl,2023-07-17,n palacio,21.0,178.0,75.0,NaN,2023.0,2026.0,RES,Right,5.0,4000.0,3600000.0,70.0,72.0,CM,287.0,53.0,64.0,53.0,72.0,45.0,300.0,63.0,44.0,53.0,66.0,74.0,362.0,70.0,71.0,73.0,74.0,74.0,328.0,60.0,60.0,78.0,63.0,317.0,63.0,70.0,65.0,70.0,49.0,54.0,195.0,63.0,70.0,62.0,45.0,12.0,10.0,6.0,5.0,12.0,rsl,NaN,264433.0
43460,91a639d5,2024-02-21,Z. MacMath,90,6,0.00,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,away,2.0,0.0,25.0,75.8,9.0,0.0,0.0,0.0,0.0,rsl,z macmath,rsl,2020-02-01,z macmath,27.0,188.0,88.0,NaN,2019.0,2020.0,GK,Right,31.0,2000.0,450000.0,66.0,65.0,GK,90.0,19.0,18.0,14.0,29.0,10.0,97.0,13.0,16.0,14.0,38.0,16.0,215.0,39.0,34.0,36.0,62.0,44.0,199.0,41.0,56.0,31.0,15.0,123.0,38.0,14.0,13.0,41.0,17.0,48.0,35.0,18.0,9.0,8.0,318.0,66.0,64.0,54.0,67.0,67.0,rsl,NaN,201940.0

In [108]:
### drop unnecessary columns and save

merged = clean_unique.drop(columns=['name_norm', 'club_norm', 'fuzzy_score','name'])

In [109]:
merged.head()

,match_id,date_x,player_name,minutes,goals,expected_goals,shot_conv_perc,on_target,pass_perc,assists,passes,cross,corner_kick,key_pass,aerial,aerial_perc,fouls,fouls_against,offside,yellow_card,red_card,side,goals_saved,goals_against,expected_goals_against,Pass,gk_throws,gk_long_balls,gk_launches,GK,corners_conceded,club,date_y,age,height_cm,weight_kg,team_name,contract_start,contract_end,position,foot,jersey_num,wage_eur,value_eur,overall_rating,best_overall,best_position,total_attacking,crossing,finishing,heading_accuracy,short_passing,volleys,total_skill,dribbling,curve,fk_accuracy,long_passing,ball_control,total_movement,acceleration,sprint_speed,agility,reactions,balance,total_power,shot_power,jumping,stamina,long_shots,total_mentality,aggression,interceptions,attack_position,vision,penalties,composure,total_defending,defensive_awareness,standing_tackle,sliding_tackle,total_goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,team_abbr,player_id
0,c1d67317,2026-03-08,T. Parker,0,0,0.00,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbny,2025-07-17,31.0,188.0,88.0,NaN,2025.0,2025.0,SUB,Right,26.0,6000.0,700000.0,67.0,67.0,CB,218.0,26.0,35.0,70.0,59.0,28.0,206.0,43.0,21.0,26.0,57.0,59.0,283.0,62.0,68.0,46.0,64.0,43.0,288.0,33.0,80.0,69.0,21.0,239.0,75.0,64.0,28.0,35.0,37.0,60.0,191.0,64.0,64.0,63.0,51.0,6.0,13.0,14.0,9.0,9.0,rbny,226803.0
1,c1d67317,2026-03-08,J. McCarthy,0,0,0.00,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbny,2025-09-19,32.0,185.0,84.0,NaN,2025.0,2025.0,RES,Right,23.0,3000.0,600000.0,68.0,68.0,GK,93.0,17.0,17.0,17.0,24.0,18.0,64.0,10.0,15.0,13.0,14.0,12.0,202.0,35.0,34.0,36.0,57.0,40.0,214.0,44.0,59.0,38.0,13.0,106.0,32.0,19.0,19.0,18.0,18.0,44.0,42.0,14.0,13.0,15.0,331.0,69.0,69.0,58.0,65.0,70.0,rbny,227909.0
3,c1d67317,2026-03-08,R. Voloder,90,0,0.04,1.0,0.0,92.1,0,58,0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbny,2026-02-05,24.0,185.0,75.0,NaN,2026.0,2026.0,LCB,Left,18.0,2000.0,550000.0,62.0,64.0,CB,194.0,32.0,23.0,56.0,56.0,27.0,208.0,49.0,29.0,25.0,50.0,55.0,301.0,63.0,69.0,56.0,55.0,58.0,256.0,42.0,66.0,59.0,20.0,215.0,50.0,62.0,28.0,35.0,40.0,52.0,194.0,63.0,66.0,65.0,59.0,12.0,10.0,8.0,14.0,15.0,rbny,256499.0
4,c1d67317,2026-03-08,J. Marshall-Rutty,77,0,0.02,1.0,0.0,94.6,0,53,0,0.0,0.0,0.0,0.0,1.0,1,0,0.0,0,home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbny,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,255335.0
5,c1d67317,2026-03-08,J. Che,90,0,0.00,0.0,0.0,88.6,0,70,0,0.0,0.0,0.0,0.0,2.0,1,0,1.0,0,home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbny,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,259159.0

In [151]:
merged.to_csv('../../data/interim/matches/players/match_players_stats_ids4.csv', index=False)

In [ ]:
### remove date oolumn

match_players = merg.drop(columns=['date'])

### rename id to player_id

match_players = match_players.rename(columns={'id': 'player_id'})

In [ ]:
### move player_id to second column

cols = match_players.columns.tolist()

cols.insert(1, cols.pop(cols.index('player_id')))

match_players = match_players[cols]

match_players